import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'headerSettings',
  title: 'Header Settings',
  type: 'document',
  groups: [
    { name: 'layout', title: 'Layout', default: true },
    { name: 'style', title: 'Header Style' },
    { name: 'mobileIcon', title: 'Mobile Icon' },
    { name: 'mobileDropdown', title: 'Mobile Dropdown' },
  ],
  fields: [
    // ── Layout ────────────────────────────────────────────────────────────────
    defineField({
      name: 'logoPosition',
      title: 'Logo Position',
      type: 'string',
      group: 'layout',
      options: {
        list: [
          { title: 'Left', value: 'left' },
          { title: 'Center', value: 'center' },
          { title: 'Right', value: 'right' },
        ],
        layout: 'radio',
      },
      initialValue: 'left',
    }),
    defineField({
      name: 'menuPosition',
      title: 'Menu Position',
      type: 'string',
      group: 'layout',
      options: {
        list: [
          { title: 'Left', value: 'left' },
          { title: 'Center', value: 'center' },
          { title: 'Right', value: 'right' },
        ],
        layout: 'radio',
      },
      initialValue: 'right',
    }),

    // ── Header Style ──────────────────────────────────────────────────────────
    defineField({
      name: 'backgroundColor',
      title: 'Background Color',
      type: 'color',
      group: 'style',
      options: { enableAlpha: true },
    }),
    defineField({
      name: 'textColor',
      title: 'Text / Link Color',
      type: 'color',
      group: 'style',
      options: { enableAlpha: true },
    }),
    defineField({
      name: 'textHoverColor',
      title: 'Text / Link Hover Color',
      type: 'color',
      group: 'style',
      options: { enableAlpha: true },
    }),
    defineField({
      name: 'fontFamily',
      title: 'Font Family',
      type: 'string',
      group: 'style',
      description: 'CSS font-family value, e.g. "Roboto, sans-serif"',
    }),
    defineField({
      name: 'fontSize',
      title: 'Font Size (px)',
      type: 'number',
      group: 'style',
    }),
    defineField({
      name: 'paddingTop',
      title: 'Padding Top (px)',
      type: 'number',
      group: 'style',
      initialValue: 16,
    }),
    defineField({
      name: 'paddingBottom',
      title: 'Padding Bottom (px)',
      type: 'number',
      group: 'style',
      initialValue: 16,
    }),
    defineField({
      name: 'paddingLeft',
      title: 'Padding Left (px)',
      type: 'number',
      group: 'style',
      initialValue: 24,
    }),
    defineField({
      name: 'paddingRight',
      title: 'Padding Right (px)',
      type: 'number',
      group: 'style',
      initialValue: 24,
    }),
    defineField({
      name: 'borderTopWidth',
      title: 'Border Top (px)',
      type: 'number',
      group: 'style',
      initialValue: 0,
    }),
    defineField({
      name: 'borderRightWidth',
      title: 'Border Right (px)',
      type: 'number',
      group: 'style',
      initialValue: 0,
    }),
    defineField({
      name: 'borderBottomWidth',
      title: 'Border Bottom (px)',
      type: 'number',
      group: 'style',
      initialValue: 0,
    }),
    defineField({
      name: 'borderLeftWidth',
      title: 'Border Left (px)',
      type: 'number',
      group: 'style',
      initialValue: 0,
    }),
    defineField({
      name: 'borderColor',
      title: 'Border Color',
      type: 'color',
      group: 'style',
      options: { enableAlpha: true },
    }),
    defineField({
      name: 'borderStyle',
      title: 'Border Style',
      type: 'string',
      group: 'style',
      options: {
        list: [
          { title: 'Solid', value: 'solid' },
          { title: 'Dashed', value: 'dashed' },
          { title: 'Dotted', value: 'dotted' },
        ],
        layout: 'radio',
      },
      initialValue: 'solid',
    }),

    // ── Mobile Icon ───────────────────────────────────────────────────────────
    defineField({
      name: 'mobileIconType',
      title: 'Mobile Menu Icon',
      type: 'string',
      group: 'mobileIcon',
      options: {
        list: [
          { title: 'Hamburger (3 lines)', value: 'hamburger' },
          { title: 'Hamburger Bold', value: 'hamburger-bold' },
          { title: 'Dots (vertical)', value: 'dots-vertical' },
          { title: 'Dots (horizontal)', value: 'dots-horizontal' },
          { title: 'Custom Image', value: 'custom' },
        ],
        layout: 'radio',
      },
      initialValue: 'hamburger',
    }),
    defineField({
      name: 'mobileIconCustom',
      title: 'Custom Icon Image',
      type: 'image',
      group: 'mobileIcon',
      description: 'Used when "Custom Image" is selected above.',
      hidden: ({ parent }) => parent?.mobileIconType !== 'custom',
    }),
    defineField({
      name: 'mobileIconColor',
      title: 'Icon Color',
      type: 'color',
      group: 'mobileIcon',
      options: { enableAlpha: true },
    }),
    defineField({
      name: 'mobileIconBackgroundColor',
      title: 'Icon Background Color',
      type: 'color',
      group: 'mobileIcon',
      options: { enableAlpha: true },
    }),
    defineField({
      name: 'mobileIconSize',
      title: 'Icon Size (px)',
      type: 'number',
      group: 'mobileIcon',
      initialValue: 28,
    }),
    defineField({
      name: 'mobileIconPadding',
      title: 'Icon Padding (px)',
      type: 'number',
      group: 'mobileIcon',
      initialValue: 4,
    }),
    defineField({
      name: 'mobileIconBorderRadius',
      title: 'Icon Border Radius (px)',
      type: 'number',
      group: 'mobileIcon',
      initialValue: 4,
    }),

    // ── Mobile Dropdown ───────────────────────────────────────────────────────
    defineField({
      name: 'mobileDropdownBackgroundColor',
      title: 'Dropdown Background Color',
      type: 'color',
      group: 'mobileDropdown',
      options: { enableAlpha: true },
    }),
    defineField({
      name: 'mobileDropdownTextColor',
      title: 'Dropdown Text / Link Color',
      type: 'color',
      group: 'mobileDropdown',
      options: { enableAlpha: true },
    }),
    defineField({
      name: 'mobileDropdownFontFamily',
      title: 'Dropdown Font Family',
      type: 'string',
      group: 'mobileDropdown',
      description: 'CSS font-family value, e.g. "Roboto, sans-serif"',
    }),
    defineField({
      name: 'mobileDropdownFontSize',
      title: 'Dropdown Font Size (px)',
      type: 'number',
      group: 'mobileDropdown',
    }),
    defineField({
      name: 'mobileDropdownPaddingX',
      title: 'Dropdown Padding Left/Right (px)',
      type: 'number',
      group: 'mobileDropdown',
      initialValue: 24,
    }),
    defineField({
      name: 'mobileDropdownPaddingY',
      title: 'Dropdown Padding Top/Bottom (px)',
      type: 'number',
      group: 'mobileDropdown',
      initialValue: 16,
    }),
    defineField({
      name: 'mobileDropdownBorderRadius',
      title: 'Dropdown Border Radius (px)',
      type: 'number',
      group: 'mobileDropdown',
      initialValue: 12,
    }),
  ],
})
